export const news = [
  {
    id: 1,
    title: "Kundé d'Or 2026 : Les grands lauréats de la musique burkinabè récompensés",
    excerpt: "La 20e édition du Kundé d'Or a célébré l'excellence musicale burkinabè avec une cérémonie exceptionnelle à Ouagadougou, réunissant les plus grands artistes du pays.",
    category: "Culture",
    date: "15 mai 2026",
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    readTime: "5 min",
    author: "Équipe BurkiNet",
  },
  {
    id: 2,
    title: "Diaspora Bonds : 40 milliards FCFA mobilisés en un mois",
    excerpt: "L'emprunt obligataire diaspora dépasse les attentes avec une souscription record, confirmant l'engouement des Burkinabè de l'extérieur pour le développement national.",
    category: "Économie",
    date: "10 mai 2026",
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    readTime: "8 min",
    author: "Équipe BurkiNet",
  },
  {
    id: 3,
    title: "Agrobusiness : Le Burkina Faso attire 3 nouveaux investisseurs internationaux",
    excerpt: "Le secteur agro-industriel burkinabè confirme son attractivité avec l'annonce de trois projets d'investissement majeurs totalisant plus de 15 milliards FCFA.",
    category: "Investissement",
    date: "3 mai 2026",
    imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    readTime: "6 min",
    author: "Équipe BurkiNet",
  },
  {
    id: 4,
    title: "Dr. Lassina Zerbo : 'Investir dans la science burkinabè, c'est investir dans l'avenir'",
    excerpt: "L'ancien secrétaire général de l'OTICE partage sa vision pour le développement scientifique du Burkina et son engagement pour la prochaine génération.",
    category: "Diaspora",
    date: "28 avril 2026",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    readTime: "10 min",
    author: "Équipe BurkiNet",
  },
  {
    id: 5,
    title: "FESPACO 2026 : Le cinéma burkinabè rayonne sur la scène internationale",
    excerpt: "La 29e édition du Festival Panafricain du Cinéma et de la Télévision de Ouagadougou affirme la place du Burkina comme capitale du cinéma africain.",
    category: "Culture",
    date: "22 avril 2026",
    imageUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80",
    readTime: "7 min",
    author: "Équipe BurkiNet",
  },
  {
    id: 6,
    title: "Énergie solaire : Le Burkina double sa capacité de production d'ici 2027",
    excerpt: "Un ambitieux programme d'expansion des centrales solaires portera la capacité nationale à 500 MW, réduisant la dépendance aux importations énergétiques.",
    category: "Énergie",
    date: "15 avril 2026",
    imageUrl: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80",
    readTime: "6 min",
    author: "Équipe BurkiNet",
  },
];

export const experts = [
  {
    id: 1,
    name: "Dr. Lassina Zerbo",
    role: "Géophysicien, ancien SG de l'OTICE",
    location: "Vienne, Autriche",
    domain: "Sciences & Diplomatie",
    bio: "Figure internationale reconnue dans le domaine de la surveillance sismique et du désarmement nucléaire, Dr. Zerbo œuvre pour le rayonnement scientifique burkinabè.",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    tags: ["Sciences", "Diplomatie", "CTBTO"],
  },
  {
    id: 2,
    name: "Dr. Boukary Sawadogo",
    role: "Professeur d'Économie, Université de Paris",
    location: "Paris, France",
    domain: "Économie & Finance",
    bio: "Économiste spécialisé dans le développement africain, il conseille plusieurs institutions internationales sur les politiques économiques en Afrique de l'Ouest.",
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
    tags: ["Économie", "Finance", "Développement"],
  },
  {
    id: 3,
    name: "Aminata Ouédraogo",
    role: "Directrice Technique, Google Africa",
    location: "Lagos, Nigeria",
    domain: "Technologie & Innovation",
    bio: "Ingénieure logicielle et leader tech, elle pilote des programmes de transformation numérique à travers le continent africain depuis Google.",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
    tags: ["Tech", "IA", "Numérique"],
  },
  {
    id: 4,
    name: "Simon Tiemtoré",
    role: "Fondateur, GVA Burkina Faso",
    location: "Ouagadougou / International",
    domain: "Entrepreneuriat & VC",
    bio: "Pionnier de l'écosystème startup burkinabè, Simon a lancé l'incubateur GVA et accompagné plus de 50 startups africaines vers la croissance.",
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    tags: ["Startups", "Fintech", "VC"],
  },
  {
    id: 5,
    name: "Fatoumata Compaoré",
    role: "Avocate Internationale, Cabinet FC & Associés",
    location: "New York, USA",
    domain: "Droit & Affaires",
    bio: "Avocate spécialisée en droit des affaires internationales et investissements en Afrique subsaharienne, elle accompagne des investisseurs dans leurs projets au Burkina.",
    imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80",
    tags: ["Droit", "Investissement", "Affaires"],
  },
  {
    id: 6,
    name: "Ibrahim Ouali",
    role: "Médecin Chercheur, OMS Genève",
    location: "Genève, Suisse",
    domain: "Santé & Recherche",
    bio: "Spécialiste en santé publique et maladies tropicales, Ibrahim coordonne des programmes de santé communautaire pour la région Afrique de l'Ouest à l'OMS.",
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80",
    tags: ["Santé", "OMS", "Recherche"],
  },
];

export const sectors = [
  {
    id: 1,
    name: "Agriculture & Agrobusiness",
    icon: "🌾",
    description: "Premier secteur économique du Burkina, l'agriculture emploie 80% de la population active.",
    indicators: [{ label: "Part du PIB", value: "32%" }, { label: "Emplois", value: "4,2M" }],
    color: "bg-green-50 border-green-200",
    accentColor: "text-green-700",
  },
  {
    id: 2,
    name: "Mines & Ressources naturelles",
    icon: "⛏️",
    description: "Le Burkina est le 4e producteur d'or en Afrique, avec un sous-sol riche en ressources minières.",
    indicators: [{ label: "Export annuel", value: "2,4 Mrd $" }, { label: "Mines actives", value: "15" }],
    color: "bg-yellow-50 border-yellow-200",
    accentColor: "text-yellow-700",
  },
  {
    id: 3,
    name: "Énergie & Électricité",
    icon: "⚡",
    description: "Fort potentiel solaire avec 300 jours d'ensoleillement par an, en plein développement.",
    indicators: [{ label: "Capacité installée", value: "250 MW" }, { label: "Taux accès élec.", value: "42%" }],
    color: "bg-orange-50 border-orange-200",
    accentColor: "text-orange-700",
  },
  {
    id: 4,
    name: "Numérique & Tech",
    icon: "💻",
    description: "Écosystème startup dynamique avec des hubs tech à Ouagadougou et Bobo-Dioulasso.",
    indicators: [{ label: "Startups actives", value: "200+" }, { label: "Taux mobile", value: "68%" }],
    color: "bg-blue-50 border-blue-200",
    accentColor: "text-blue-700",
  },
  {
    id: 5,
    name: "Tourisme & Artisanat",
    icon: "🏛️",
    description: "Riche patrimoine culturel et artisanat reconnu mondialement, notamment le tissage traditionnel.",
    indicators: [{ label: "Visiteurs/an", value: "380 000" }, { label: "Recettes", value: "65 Mrd FCFA" }],
    color: "bg-purple-50 border-purple-200",
    accentColor: "text-purple-700",
  },
  {
    id: 6,
    name: "Immobilier & Construction",
    icon: "🏗️",
    description: "Marché immobilier en forte croissance, porté par l'urbanisation rapide et les investisseurs diaspora.",
    indicators: [{ label: "Croissance sect.", value: "+8%/an" }, { label: "Logements besoin", value: "250 000" }],
    color: "bg-red-50 border-red-200",
    accentColor: "text-red-700",
  },
];

export const economicData = {
  gdp: { value: "20,2", unit: "Mrd USD", change: "+6,5%", year: "2025" },
  population: { value: "23,5", unit: "millions", change: "+2,9%/an", year: "2025" },
  inflation: { value: "3,2", unit: "%", change: "-1,8pt", year: "2025" },
  fdi: { value: "420", unit: "M USD", change: "+12%", year: "2025" },
  exports: { value: "3,1", unit: "Mrd USD", change: "+5%", year: "2025" },
  regions: 13,
};

export const successStories = [
  {
    id: 1,
    name: "Dr. Lassina Zerbo",
    title: "De Toma à l'OTICE de Vienne",
    excerpt: "Né dans un petit village du Burkina, il est devenu l'un des scientifiques les plus influents au monde dans la lutte contre les essais nucléaires.",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
    country: "🇦🇹 Autriche",
    domain: "Sciences",
  },
  {
    id: 2,
    name: "Rasmané Ouédraogo",
    title: "Entrepreneur tech à succès depuis Paris",
    excerpt: "Fondateur d'une fintech africaine valorisée à 50 M€, Rasmané a prouvé que l'innovation africaine peut conquérir les marchés européens.",
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&q=80",
    country: "🇫🇷 France",
    domain: "Tech",
  },
  {
    id: 3,
    name: "Mariam Traoré",
    title: "La cheffe qui a mis la cuisine burkinabè sur la carte mondiale",
    excerpt: "Son restaurant à Montréal, élu meilleure table africaine du Canada, est devenu un ambassadeur de la culture burkinabè à l'international.",
    imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&q=80",
    country: "🇨🇦 Canada",
    domain: "Gastronomie",
  },
];

export const diasporaGuides = [
  {
    title: "Investir au Burkina depuis l'étranger",
    steps: ["Créer une entreprise en ligne via CEFORE", "Ouvrir un compte bancaire professionnel", "Accéder aux incitations fiscales pour la diaspora", "Contacter les facilitateurs APEC"],
    icon: "💼",
  },
  {
    title: "Revenir s'installer au Burkina",
    steps: ["Reconnaissance des diplômes étrangers", "Logement : quartiers et prix à Ouagadougou", "Santé : cliniques et couverture maladie", "Scolarité des enfants"],
    icon: "🏠",
  },
  {
    title: "Transfert d'argent vers le Burkina",
    steps: ["Meilleures plateformes de transfert (Western Union, Wave, Orange Money)", "Taux de change et frais comparés", "Investir via les Diaspora Bonds", "Dons aux associations"],
    icon: "💸",
  },
];
